### ISSUE TITLE
When Granota is being used a lot, crashes.

### ISSUE THREAD

**Issue by jeda** [CatIRCBots/Granota#21]
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python27\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python27\lib\asyncore.py", line 449, in handle_read_event
    self.handle_read()
  File "C:\Python27\lib\asynchat.py", line 165, in handle_read
    self.found_terminator()
  File "C:\Users\Enrique\Granota\willie\irc.py", line 455, in found_terminator
    self.dispatch(origin, text, args)
  File "C:\Users\Enrique\Granota\willie\bot.py", line 730, in dispatch
    t.start()
  File "C:\Python27\lib\threading.py", line 745, in start
    _start_new_thread(self.__bootstrap, ())
error: can't start new thread

[irc.pyc] Fatal error in core, please review exception log
Too many errors, can't continue

**Comment by mikicat** [comment]
No idea what to do...

**Comment by jeda** [comment]
Probably we should rewrite the code that will not start a thread for that, then we prevent it to crash.

**Comment by jeda** [comment]
Reliving this issue:

Probably we may need to use another IRC framework, as the thread stuff is on asyncore, which we cannot modify (?)

**Comment by NeoMahler** [comment]
But I ask... why should we send 4 messages every second aprox. during more than 1 minute? If I remember, the test constisted of four spambots spamming at the same time during a while...

**Comment by NeoMahler** [comment]
@JeDa do you mind if I close this issue? Seems irrellevant to me.

**Comment by NeoMahler** [comment]
Closing
