### ISSUE TITLE
,seen is reset when the bot is reloaded

### ISSUE THREAD

**Issue by NeoMahler** [CatIRCBots/Granota#60]
If the the bot is reloaded, the bot "forgets" the nicks it has seen. Proposed solution: use a separate file (json? txt?)

**Comment by NeoMahler** [comment]
@ElGatoSaez: any idea on how to fix this error?

```
Traceback (most recent call last):
  File "/home/neomahler/Granota-freenode/willie/bot.py", line 675, in call
    exit_code = func(willie, trigger)
  File "/home/neomahler/Granota-freenode/willie/modules/seen.py", line 63, in note
    data[name]['timestamp'] = time.time()
TypeError: 'Nick' object does not support item assignment
```

**Comment by NeoMahler** [comment]
Done
